app_course:
    resource: "@AppBundle/Resources/config/routing/course.yml"
    prefix:   /course

<<<<<<< HEAD
app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user
=======
app_file:
    resource: "@AppBundle/Resources/config/routing/file.yml"
    prefix:   /file
>>>>>>> 8691ff6bfb981fa8fc7f1d8b41968de99cc83e53
