AppBundle\Entity\Course:
  properties:
    nazwa:
      - NotBlank: ~
      - Length:
          min: 5
          max: 255

AppBundle\Entity\File:
  properties:
    nazwa:
      - NotBlank: ~
      - Length:
          min: 5
          max: 255
    sciezka:
      - File:
          maxSize: 2M
          mimeTypes: [application/pdf, application/x-pdf]
          mimeTypesMessage: Można wgrać tylko plik PDF

AppBundle\Entity\User:
  properties:
    username:
      - Length:
          min: 7
          max: 7
          exactMessage: Nazwa użytkownika powinna zawierać dokładnie 7 znaków.
#    password:
#      - Length:
#          min: 8
#          max: 32
#          exactMessage: Hasło użytkownika powinno zawierać od 8 do 32 znaków.

    enabled:
      - Choice: [0, 1]